DROP TABLE IF EXISTS relationship_load CASCADE;
DROP TABLE IF EXISTS versions CASCADE;
DROP TABLE IF EXISTS twitter_account CASCADE;
DROP TABLE IF EXISTS relationship_event CASCADE;
DROP TYPE  IF EXISTS event_verb CASCADE;
